name: Generate Daily Report

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Ensure data directory exists
        run: mkdir -p data

      - name: Generate report with Gemini
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          REPORT_PROMPT: '今日のポイ活最新情報をまとめてください'
        run: |
          python src/generate_report.py > data/$(date +'%Y-%m-%d').md

      - name: Generate index.html
        run: |
          python src/generate_index.py

      - name: Commit and push report
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/*.md
          git commit -m "Add daily report $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push

      - name: Commit and push index.html
        run: |
          git add index.html
          git commit -m "Update index.html" || echo "No changes to commit"
          git push
